import './core/client.js';
import './views/field.js';
import './views/form/form_compiler.js';
import './views/form/form_view.js';
import './views/form/form_controller.js';
import './tooltip/js/dev_info_service.js';
import './tooltip/js/tooltip.js';
import './views/list/list_renderer.js';
import './views/view_button/view_button.js';